spring.application.name=administracion
 
# ═══ MAIL ═══
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kbedonv@uteq.edu.ec
spring.mail.password=azwlnzjmjzwvqexe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# ═══ URLs MICROSERVICIOS ═══
microservicio.facturacion.url=http://74.249.40.210:8080
 
server.port=8081
 